import dotenv from "dotenv";
import { environments } from "../constants/app.config.js";
const path = `.env.${process.env.NODE_ENV}.local`;
dotenv.config({ path });
let {
  PORT,
  OTP_HASH_SECRET,
  SMS_SERVICE_SID,
  SMS_SERVICE_AUTH_TOKEN,
  SMS_SERVICE_SENDER_NUMBER,
  DATABASE_URL,
  JWT_ACCESS_TOKEN_SECRET,
  JWT_REFRESH_TOKEN_SECRET,
  REDIS_PORT,
  REDIS_HOST,
  REDIS_USER_PASSWORD,
  NODE_ENV,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  VAPID_KEY_PUBLIC,
  VAPID_KEY_PRIVATE,
  GCM_API_KEY,
  FRONTEND_URL,
} = process.env;

console.log(process.env.NODE_ENV);

const ENVIRONMENT_DEV = NODE_ENV === environments.dev;
const ENVIRONMENT_PROD = NODE_ENV === environments.prod;
const ENVIRONMENT_UAT = NODE_ENV === environments.uat;

export {
  PORT,
  OTP_HASH_SECRET,
  SMS_SERVICE_SID,
  SMS_SERVICE_AUTH_TOKEN,
  SMS_SERVICE_SENDER_NUMBER,
  DATABASE_URL,
  JWT_ACCESS_TOKEN_SECRET,
  JWT_REFRESH_TOKEN_SECRET,
  REDIS_PORT,
  REDIS_HOST,
  REDIS_USER_PASSWORD,
  NODE_ENV,
  ENVIRONMENT_DEV,
  ENVIRONMENT_UAT,
  ENVIRONMENT_PROD,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  VAPID_KEY_PRIVATE,
  VAPID_KEY_PUBLIC,
  GCM_API_KEY,
  FRONTEND_URL,
};
